version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: "pg-docker"
    restart: always
    # env_file:
    #   - ./config/dev.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  # api:
  #   build: .
  #   command: cd /app pipenv shell python manage.py runserver 0.0.0.0:4000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - postgres

volumes:
  postgres:
